######################################################################
##
## Filename: cpu.udo
## Created on: Thu Jun 11 19:31:50 中国标准时间 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
