######################################################################
##
## Filename: TEXT.udo
## Created on: Thu Jun 11 17:30:09 中国标准时间 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
